### ISSUE TITLE
Updated usage and structure documentation

### ISSUE THREAD

**Issue by scasplte2** [Topl/Prosomo#17]
- [x] Update all available commands
- [x] Diagram actor relationships in autonomous prosomo
- [x] Describe responsibilities of actors
- [ ] Describe runtime processes in prosomo ( what loops are happening at what timescales, who dependents on who for data, etc.)

**Comment by aaronschutza** [comment]
Issue has been made an initiative and will track all documentation and usages updates
