### ISSUE TITLE
Integrating network controller into prosomo architecture

### ISSUE THREAD

**Issue by aaronschutza** [Topl/Prosomo#6]
The next major hurdle is integration of network communication.  The plan is to use the Bifrost infrastructure as a starting template.

- [x] Write serializers for all prosomo remote messages
- [x] Initialize the network controller in the same actor context as the Stakeholders
- [x] Interface the Router actor with the Network controller for passing remote messages
- [ ] Pass a serialized message from one actor to another locally using the Network controller

**Comment by aaronschutza** [comment]
Network actors are now running along side simulation actors without Bifrost actors.  I plan on making the router actor interface with network components.

**Comment by aaronschutza** [comment]
Router now registers with the network controller and interacts with messages from remote on its own set of message codes and specifications.  The serializers for all remote messages have been written.

**Comment by aaronschutza** [comment]
Holder refs are now handled by a wrapper class in order to represent remote actors and local actors in the same class

**Comment by aaronschutza** [comment]
The unmodified network controller and peer manager has been integrated into prosomo.  The router registers with the network controller as the handler for all prosomo messages.  Bifrost messages can still be interpreted in the same context.
